apiVersion: 1

# Grafana otomatik datasource tanımı
# Bu dosya, Grafana başlatıldığında Flask API'yi datasource olarak ekler.
# Manuel ekleme gerekmez.

datasources:
  - name: IoT Flask API
    type: simplejson
    access: proxy
    url: http://flask_api:5000
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "2s"
